language: python
python:
    - "2.7"
    
env:
- TOX_ENV=py27
- TOX_ENV=py33
- TOX_ENV=py34

before_install:
    - sudo apt-get install python-numpy python-scipy 

install: 
    - pip install --install-option="--no-cython-compile" Cython
    - pip install tox
script:
    - tox -e $TOX_ENV
