language: python
python:
    - "2.7"
    
env:
- TOX_ENV=py27
- TOX_ENV=py33
- TOX_ENV=py34

install: 
    - pip install --install-option="--no-cython-compile" Cython
    - pip install tox
    - pip install numpy
    - pip install pytest

script:
    - tox -e $TOX_ENV
